import emojiJson from "@perfice/assets/emojis.json?raw";
import {
    faAnchor,
    faBacon,
    faBandage,
    faBatteryEmpty,
    faBatteryFull,
    faBatteryHalf,
    faBatteryQuarter,
    faBatteryThreeQuarters,
    faBed,
    faBell,
    faBicycle,
    faBook,
    faBowlRice,
    faBrain,
    faBullseye,
    faCandyCane,
    faCar,
    faCircle,
    faCloudMeatball,
    faComputer,
    faCow,
    faDroplet,
    faDrumstickBite,
    faDumbbell,
    faEnvelope,
    faFish,
    faFlag,
    faGamepad,
    faGlassWater,
    faGuitar,
    faHamburger,
    faHandsHoldingCircle,
    faHashtag,
    faHeart,
    faLaptop,
    faLeaf,
    faLemon,
    faList,
    faLocation,
    faMobileScreen,
    faMoneyBill,
    faMoon,
    faMugHot,
    faPersonFallingBurst,
    faPersonPraying,
    faPersonWalking,
    faPills,
    faPoop,
    faShoePrints,
    faShower,
    faSmoking,
    faSnowflake,
    faSquareCheck,
    faStar,
    faSun,
    faTag,
    faTemperatureHalf,
    faWeightScale,
    faWineGlass,
    faYinYang,
    type IconDefinition
} from "@fortawesome/free-solid-svg-icons";

import {
    faFaceDizzy,
    faFaceFrown,
    faFaceLaughBeam,
    faFaceMeh,
    faFaceSmile,
    faFaceTired
} from "@fortawesome/free-regular-svg-icons";

export interface Emoji {
    emoji: string;
    annotation: string;
    tags: string;
}

export const EMOJIS: Emoji[] = JSON.parse(emojiJson);

export const ICONS: Record<string, IconDefinition> = {
    "star": faStar,
    "book": faBook,
    "flag": faFlag,
    "shower": faShower,
    "square_check": faSquareCheck,
    "guitar": faGuitar,
    "smoking": faSmoking,
    "computer": faComputer,
    "hands_circle": faHandsHoldingCircle,
    "candy_cane": faCandyCane,
    "person_falling": faPersonFallingBurst,
    "game_pad": faGamepad,
    "dumbbell": faDumbbell,
    "moon": faMoon,
    "heart": faHeart,
    "phone": faMobileScreen,
    "glass": faGlassWater,
    "scale": faWeightScale,
    "shoes": faShoePrints,
    "coffee": faMugHot,
    "laptop": faLaptop,
    "bike": faBicycle,
    "car": faCar,
    "fish": faFish,
    "blood": faDroplet,
    "leaf": faLeaf,
    "list": faList,
    "sun": faSun,
    "bed": faBed,
    "lemon": faLemon,
    "money": faMoneyBill,
    "snowflake": faSnowflake,
    "anchor": faAnchor,
    "circle": faCircle,
    "mail": faEnvelope,
    "bell": faBell,
    "drink": faWineGlass,
    "smile": faFaceSmile,
    "laugh": faFaceLaughBeam,
    "meh": faFaceMeh,
    "tired": faFaceTired,
    "frown": faFaceFrown,
    "brain": faBrain,
    "battery_full": faBatteryFull,
    "battery_empty": faBatteryEmpty,
    "battery_half": faBatteryHalf,
    "battery_quarter": faBatteryQuarter,
    "battery_three_quarter": faBatteryThreeQuarters,
    "cloud_meatball": faCloudMeatball,
    "hashtag": faHashtag,
    "dizzy": faFaceDizzy,
    "droplet": faDroplet,
    "temperature": faTemperatureHalf,
    "bandage": faBandage,
    "tag": faTag,
    "hamburger": faHamburger,
    "pills": faPills,
    "person_walking": faPersonWalking,
    "person_praying": faPersonPraying,
    "location": faLocation,
    "poop": faPoop,
    "rice": faBowlRice,
    "chicken": faDrumstickBite,
    "bacon": faBacon,
    "cow": faCow,
    "yin_yang": faYinYang,
    "bullseye": faBullseye,
}

