// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUsersTimeZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersTimeZonesRequest) Reset() {
	*x = GetUsersTimeZonesRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersTimeZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersTimeZonesRequest) ProtoMessage() {}

func (x *GetUsersTimeZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersTimeZonesRequest.ProtoReflect.Descriptor instead.
func (*GetUsersTimeZonesRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersTimeZonesRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersTimeZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezones     map[string]string      `protobuf:"bytes,1,rep,name=timezones,proto3" json:"timezones,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersTimeZonesResponse) Reset() {
	*x = GetUsersTimeZonesResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersTimeZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersTimeZonesResponse) ProtoMessage() {}

func (x *GetUsersTimeZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersTimeZonesResponse.ProtoReflect.Descriptor instead.
func (*GetUsersTimeZonesResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersTimeZonesResponse) GetTimezones() map[string]string {
	if x != nil {
		return x.Timezones
	}
	return nil
}

type GetUserTimeZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTimeZoneRequest) Reset() {
	*x = GetUserTimeZoneRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTimeZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTimeZoneRequest) ProtoMessage() {}

func (x *GetUserTimeZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTimeZoneRequest.ProtoReflect.Descriptor instead.
func (*GetUserTimeZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserTimeZoneRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserTimeZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timezone      string                 `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTimeZoneResponse) Reset() {
	*x = GetUserTimeZoneResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTimeZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTimeZoneResponse) ProtoMessage() {}

func (x *GetUserTimeZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTimeZoneResponse.ProtoReflect.Descriptor instead.
func (*GetUserTimeZoneResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserTimeZoneResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Expiry        int64                  `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type SuccessfulAuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessfulAuthenticationResponse) Reset() {
	*x = SuccessfulAuthenticationResponse{}
	mi := &file_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulAuthenticationResponse) ProtoMessage() {}

func (x *SuccessfulAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*SuccessfulAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SuccessfulAuthenticationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SuccessfulAuthenticationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AuthenticationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*AuthenticationResponse_Auth
	//	*AuthenticationResponse_Error
	Result        isAuthenticationResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *AuthenticationResponse) GetResult() isAuthenticationResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AuthenticationResponse) GetAuth() *SuccessfulAuthenticationResponse {
	if x != nil {
		if x, ok := x.Result.(*AuthenticationResponse_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *AuthenticationResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*AuthenticationResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isAuthenticationResponse_Result interface {
	isAuthenticationResponse_Result()
}

type AuthenticationResponse_Auth struct {
	Auth *SuccessfulAuthenticationResponse `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type AuthenticationResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AuthenticationResponse_Auth) isAuthenticationResponse_Result() {}

func (*AuthenticationResponse_Error) isAuthenticationResponse_Result() {}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\"-\n" +
	"\x15AuthenticationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\",\n" +
	"\x12GetSessionsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x18GetUsersTimeZonesRequest\x12\x18\n" +
	"\auserIds\x18\x01 \x03(\tR\auserIds\"\xa2\x01\n" +
	"\x19GetUsersTimeZonesResponse\x12G\n" +
	"\ttimezones\x18\x01 \x03(\v2).GetUsersTimeZonesResponse.TimezonesEntryR\ttimezones\x1a<\n" +
	"\x0eTimezonesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x16GetUserTimeZoneRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x17GetUserTimeZoneResponse\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\";\n" +
	"\x13GetSessionsResponse\x12$\n" +
	"\bsessions\x18\x01 \x03(\v2\b.SessionR\bsessions\"I\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\x03R\x06expiry\"X\n" +
	" SuccessfulAuthenticationResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tsessionId\x18\x02 \x01(\tR\tsessionId\"s\n" +
	"\x16AuthenticationResponse\x127\n" +
	"\x04auth\x18\x01 \x01(\v2!.SuccessfulAuthenticationResponseH\x00R\x04auth\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result2\x9a\x02\n" +
	"\vUserService\x12?\n" +
	"\fAuthenticate\x12\x16.AuthenticationRequest\x1a\x17.AuthenticationResponse\x128\n" +
	"\vGetSessions\x12\x13.GetSessionsRequest\x1a\x14.GetSessionsResponse\x12D\n" +
	"\x0fGetUserTimeZone\x12\x17.GetUserTimeZoneRequest\x1a\x18.GetUserTimeZoneResponse\x12J\n" +
	"\x11GetUsersTimeZones\x12\x19.GetUsersTimeZonesRequest\x1a\x1a.GetUsersTimeZonesResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_auth_proto_goTypes = []any{
	(*AuthenticationRequest)(nil),            // 0: AuthenticationRequest
	(*GetSessionsRequest)(nil),               // 1: GetSessionsRequest
	(*GetUsersTimeZonesRequest)(nil),         // 2: GetUsersTimeZonesRequest
	(*GetUsersTimeZonesResponse)(nil),        // 3: GetUsersTimeZonesResponse
	(*GetUserTimeZoneRequest)(nil),           // 4: GetUserTimeZoneRequest
	(*GetUserTimeZoneResponse)(nil),          // 5: GetUserTimeZoneResponse
	(*GetSessionsResponse)(nil),              // 6: GetSessionsResponse
	(*Session)(nil),                          // 7: Session
	(*SuccessfulAuthenticationResponse)(nil), // 8: SuccessfulAuthenticationResponse
	(*AuthenticationResponse)(nil),           // 9: AuthenticationResponse
	nil,                                      // 10: GetUsersTimeZonesResponse.TimezonesEntry
}
var file_proto_auth_proto_depIdxs = []int32{
	10, // 0: GetUsersTimeZonesResponse.timezones:type_name -> GetUsersTimeZonesResponse.TimezonesEntry
	7,  // 1: GetSessionsResponse.sessions:type_name -> Session
	8,  // 2: AuthenticationResponse.auth:type_name -> SuccessfulAuthenticationResponse
	0,  // 3: UserService.Authenticate:input_type -> AuthenticationRequest
	1,  // 4: UserService.GetSessions:input_type -> GetSessionsRequest
	4,  // 5: UserService.GetUserTimeZone:input_type -> GetUserTimeZoneRequest
	2,  // 6: UserService.GetUsersTimeZones:input_type -> GetUsersTimeZonesRequest
	9,  // 7: UserService.Authenticate:output_type -> AuthenticationResponse
	6,  // 8: UserService.GetSessions:output_type -> GetSessionsResponse
	5,  // 9: UserService.GetUserTimeZone:output_type -> GetUserTimeZoneResponse
	3,  // 10: UserService.GetUsersTimeZones:output_type -> GetUsersTimeZonesResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	file_proto_auth_proto_msgTypes[9].OneofWrappers = []any{
		(*AuthenticationResponse_Auth)(nil),
		(*AuthenticationResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
